---
title: "Penguins Exploration"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

```{r}
penguins <- read_csv("penguins.csv")
```

```{r}
penguins %>%
  filter(!is.na(sex)) %>%
  ggplot(aes(flipper_length_mm, bill_length_mm, color = sex, size = body_mass_g)) +
  geom_point(alpha = 0.7) +
  facet_wrap(~ species)
```

```{r}
penguins_df <- penguins %>%
  filter(!is.na(sex)) %>%
  select(-year, -island) %>%
  mutate(sex = as.factor(sex))
```

## Split the data and bootstrap it

```{r}
library(tidymodels)
set.seed(123)
penguin_split <- initial_split(penguins_df, strata = sex)
penguin_train <- training(penguin_split)
penguin_test <- testing(penguin_split)
set.seed(234)
penguin_boot <- bootstraps(penguin_train)
penguin_boot
```

## Build out the model

```{r}
library(ranger)

glm_spec <- logistic_reg() %>%
  set_engine("glm")

rf_spec <- rand_forest() %>%
  set_mode("classification") %>%
  set_engine("ranger")
```

## Establish the workflow

```{r}
penguin_workflow <- workflow() %>%
  add_formula(sex ~ .)
```

## Add models to the workflow

```{r}
glm_rs <- penguin_workflow %>%
  add_model(glm_spec) %>%
  fit_resamples(
    resamples = penguin_boot,
    control = control_resamples(save_pred = TRUE, verbose = TRUE)
  )

rf_rs <- penguin_workflow %>%
  add_model(rf_spec) %>%
  fit_resamples(
    resamples = penguin_boot,
    control = control_resamples(save_pred = TRUE, verbose = TRUE)
  )
```

## Evaluate the models

```{r}
collect_metrics(rf_rs)
```

```{r}
collect_metrics(glm_rs)
```

```{r}
glm_rs %>%
  conf_mat_resampled()
```

```{r}
glm_rs %>%
  collect_predictions() %>%
  group_by(id) %>%
  roc_curve(sex, .pred_female) %>%
  ggplot(aes(1 - specificity, sensitivity, color = id)) +
  geom_abline(lty = 2, color = "gray80", size = 1.5) +
  geom_path(show.legend = FALSE, alpha = 0.6, size = 1.2) +
  coord_equal()
```

```{r}
penguin_final <- penguin_workflow %>%
  add_model(glm_spec) %>%
  last_fit(penguin_split)

collect_metrics(penguin_final)
```

```{r}
penguin_final$.workflow[[1]] %>%
  tidy(exponentiate = TRUE) %>%
  arrange(estimate)
```

