---
title: "Analysis of IKEA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Get the libraries

```{r}
library(tidyverse)
library(tidymodels)
```

## Get the data

```{r}
ikea <- read_csv("ikea.csv")
```

```{r}
ikea %>%
  ggplot(aes(width, price)) +
  geom_point(alpha = 0.4) +
  scale_y_log10()
```

```{r}
ikea %>%
  select(X1, price, depth:width) %>%
  pivot_longer(depth:width, names_to = "dim") %>%
  ggplot(aes(value, price, color = dim)) +
  geom_point(alpha = 0.4, show.legend = FALSE) +
  scale_y_log10() +
  facet_wrap(~ dim, scales = "free_x") +
  labs(x = NULL)
```

## What names are there

```{r}
ikea %>%
  count(name, sort = TRUE)
```


```{r}
ikea_df <- ikea %>%
  select(price, name, category, depth, height, width) %>%
  mutate(price = log10(price)) %>%
  mutate_if(is.character, factor)
```

## Build a model

```{r}
set.seed(123)

ikea_split <- initial_split(ikea_df, strata = price)
ikea_train <- training(ikea_split)
ikea_test <- testing(ikea_split)

set.seed(234)
ikea_folds <- bootstraps(ikea_train, strata = price)
ikea_folds
```

```{r}
library(usemodels)

use_ranger(price ~ ., data = ikea_train)
```

```{r}
library(textrecipes)

ranger_recipe <- recipe(formula = price ~ ., data = ikea_train) %>%
  step_other(name, category, threshold = 0.01) %>%
  step_clean_levels(name, category) %>%
  step_knnimpute(depth, height, width)

ranger_spec <- rand_forest(mtry = tune(), min_n = tune(), trees = 1000) %>%
  set_mode("regression") %>%
  set_engine("ranger")

ranger_workflow <- workflow() %>%
  add_recipe(ranger_recipe) %>%
  add_model(ranger_spec)

set.seed(8577)
doParallel::registerDoParallel()
ranger_tune <- tune_grid(ranger_workflow, resamples = ikea_folds, grid = 11)
```

## Explore results of finished model

```{r}
show_best(ranger_tune, metric = "rmse")
show_best(ranger_tune, metric = "rsq")
```

```{r}
autoplot(ranger_tune)
```

```{r}
final_rf <- ranger_workflow %>%
  finalize_workflow(select_best(ranger_tune, metric = "rmse"))
```

## Fit the final workflow to the train and test data

```{r}
ikea_fit <- last_fit(final_rf, ikea_split)
```

## Now collect the metrics

```{r}
collect_metrics(ikea_fit)
```

## Now collect the predictions

```{r}
collect_predictions(ikea_fit) %>%
  ggplot(aes(price, .pred)) +
  geom_abline(lty = 2, color = "gray50") +
  geom_point(alpha = 0.5, color = "midnightblue") +
  coord_fixed()
```
